name: Deploy to Raspberry Pi

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: [self-hosted, Linux, ARM]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        run: |
          # cd mainsail
          npm ci

      - name: Build
        run: |
          # cd mainsail  
          npm run build

      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.PI_HOST }}
          username: pi
          key: ${{ secrets.PI_SSH_KEY }}
          script: |
            rm -rf /var/www/html/*
            tar -czf - -C mainsail/dist . | tar -xzf - -C /var/www/html/

      - name: Set permissions
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.PI_HOST }}
          username: pi
          key: ${{ secrets.PI_SSH_KEY }}
          script: |
            sudo chown -R www-data:www-data /var/www/html/
            sudo chmod -R 755 /var/www/html/
            sudo systemctl reload nginx
